version: '3.2'
services:
  command-adapter-v1:
    image: command-adapter-v1:latest
    hostname: command-adapter-v1
    restart: always
    ports:
      - 8181:8181
    environment:
      - JAVA_OPTIONS=-Xms256m -Xmx256m -server -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
      - KAFKA_HOSTS=kafka:9092
  command-handler-v1:
    image: command-handler-v1:latest
    hostname: command-handler-v1
    restart: always
    ports:
    - 8183:8183
    environment:
    - JAVA_OPTIONS=-Xms256m -Xmx256m -server -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
    - KAFKA_HOSTS=kafka:9092
    - PG_URL=jdbc:postgresql://postgres:5432/ticket_v1
  query-adapter-v1:
    image: query-adapter-v1:latest
    hostname: query-adapter-v1
    restart: always
    ports:
    - 8182:8182
    environment:
    - JAVA_OPTIONS=-Xms256m -Xmx256m -server -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
    - PG_URL=jdbc:postgresql://postgres:5432/ticket_v1
networks:
  default:
    external:
      name: postgresql_default